sudo: false

language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt -t lib

# Cache Gcloud SDK between commands
cache:
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"
  - lib

before_deploy:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- openssl aes-256-cbc -K $encrypted_897aefb8652c_key -iv $encrypted_897aefb8652c_iv
  -in gcp-secret.json.enc -out gcp-secret.json -d
- gcloud auth activate-service-account --key-file gcp-secret.json
- gcloud config set project $GCP_PROJECT

deploy:
  provider: script
  script:
    - ./deploy.sh $GCP_PROJECT